server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manage?useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-wait-millis: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 3600000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml

redis:
  host: localhost
  database: 0
  port: 6379
  password:
  jedis:
    pool:
      max-active: 8
      max-wait: -1ms
      max-idle: 8
      min-idle: 0
  timeout: 3000ms

logging:
  level:
    com.manage.mapper: debug

#spring:
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: manage
#data:
#  elasticsearch:
#    repositories:
#      enabled: true
#    cluster-nodes: 127.0.0.1:9300
#    cluster-name: elasticsearch
